### ISSUE TITLE
 No module named 'requests_futures.sessions'

### ISSUE THREAD

**Issue by Macile** [ross/requests-futures#100]
python3.7.8
I have install ,but still can't import 
![image](https://user-images.githubusercontent.com/26572845/98096761-1ab00300-1ec7-11eb-9e01-77943c3b3368.png)

**Comment by ross** [comment]
This looks likely to be something wrong with your dev environment rather than requests_futures.  As you can see in the docs & tests the import line is correct there.

**Comment by snooppr** [comment]
The problem is in the name of the program.  The program name must never be the same as the imported library name.  Just rename your "requests_futures" file -> program.py.
