### ISSUE TITLE
Not showing as updated on PyPI

### ISSUE THREAD

**Issue by JonnoFTW** [ross/requests-futures#125]
Currently, PyPI reports that this project was last updated on Jun 11, 2019 because that's when the source was last updated. https://pypi.org/project/requests-futures/#history

Can you update the source distribution to match the wheel so that people know this project is actively maintained? 

A new release with the updated requirements.txt would be nice too.

**Comment by ross** [comment]
> Currently, PyPI reports that this project was last updated on Jun 11, 2019 because that's when the source was last updated. https://pypi.org/project/requests-futures/#history

That was the last meaningful change/release, the rest are just ancillary/housekeeping stuff. 

> Can you update the source distribution to match the wheel so that people know this project is actively maintained?

I'd have to cut a release with no actual changes to get pypi to say anything new. This repo isn't abandoned, it just does what it needs to do and there hasn't been any changes necessary recently. 

> A new release with the updated requirements.txt would be nice too.

requirements.txt isn't part of the released artifacts. It can be updated easily enough, but wouldn't change the built package.
