### ISSUE TITLE
ThreadPoolExecutor resource cleanup?

### ISSUE THREAD

**Issue by boboli** [ross/requests-futures#20]
When using `FuturesSession` for a long-running web scraper script, I've noticed a memory leak due to the fact that I wasn't cleaning up the `ThreadPoolExecutor`s that were created by the many `FuturesSession(max_workers=blah)` calls I was making.

I fixed the issue by writing a contextmanager that cleaned up my executor when exiting:
```python
@contextmanager
def clean_futures_session_when_done(session):
    try:
        yield
    finally:
        if session.executor:
            session.executor.shutdown()

with clean_futures_session_when_done(FuturesSession(max_workers=2)):
    do_stuff()
```
This feels a bit slimy since I'm using the internal(?) `self.executor` reference. I also realize that the `shutdown()` will block until all `Future`s are done, but I feel this is acceptable for many use cases.

An alternative I've considered is having `FuturesSession` implement the context manager protocol with `__enter__()` and `__exit__()` so we can directly use it in a with statement. This would be similar to how `open()` works:

```python
class FuturesSessionWithCleanup(FuturesSession):
    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        self.executor.shutdown()

with FuturesSessionWithCleanup(max_workers=2):
    do_stuff()
# block until all Futures are cleaned
```

Does this sound reasonable?

**Comment by jamiesonbecker** [comment]
+1. Seems useful when chunking large numbers of requests (I'm doing 5000 per FuturesSession)

**Comment by ross** [comment]
happy to accept patches w/tests. otherwise i'll try and get to it in an upcoming weekend.

**Comment by boboli** [comment]
Heh I was dragging my feet on the PR because of the difficulty of writing a proper unit test. I've investigated the `concurrent.futures` module, and there's only 2 ways I can think of to determine if the executor has been shutdown:

1. Inspect `executor._shutdown` which is a private field on `ThreadPoolExecutor` (https://hg.python.org/cpython/file/3.2/Lib/concurrent/futures/thread.py#l125). Feels really icky to rely on private API.
2. Rely on the documented fact that a `RuntimeError` will be raised if we try to use the `ThreadPoolExectuor` again: (https://docs.python.org/3.2/library/concurrent.futures.html#concurrent.futures.Executor.shutdown): "Calls to Executor.submit() and Executor.map() made after shutdown will raise RuntimeError."

Option 2 sounds slightly more proper but still icky in that it's not directly asserting what we intended, but a side effect.

Lemme know which option sounds better and I can try to do a PR with it.

**Comment by ross** [comment]
another option might be to monkey patch executor.shutdown in the unit test and replace it with something that sets a flag and calls the original.

or slightly cleaner, inherit from FuturesSession and override __exit__ and set a flag that can be checked there. 

definitely a tough thing to test, that it shut down as designed. i guess the most important part to test is that the object functions in the with context correctly. that it calls __exit__ is nice to test, but not critical.
