### ISSUE TITLE
Futures still alive when an exception is thrown

### ISSUE THREAD

**Issue by rififi** [ross/requests-futures#23]
Hi,

I've been using requests-futures for some months now, and it's really a great tool.

However, for a few days, I've been looking more closely to the number of process started by a Session.

When a future finishes normally, with no timeOut exception or anything like that, the future is freed from the memory, and the process affiliated with the future disappears. When an exception is thrown, the process stays alive.

I tried many things, like session.executor.shutdown(), but I couldn't fix the issue. It seems that when an exception is raised, the future is still "marked" as pending.

Do you have an idea about how to solve this issue ?

**Comment by ross** [comment]
can't seem to reproduce this problem with 500/timeout requests against httpbin on linux or osx and python 2.7. if you can provide an example of the problem and info about where you're getting it i'd be happy to take another look.

```
#!/usr/bin/env python
#
#


from os import getpid
from requests_futures.sessions import FuturesSession
from time import sleep

session = FuturesSession(max_workers=4)


print "sleeping: %d" % getpid()
sleep(10)
print "starting"


futures = []
for i in range(5):
  #futures.append(session.get('http://httpbin.org/status/200'))
  #futures.append(session.get('http://httpbin.org/status/500'))
  futures.append(session.get('http://httpbin.org/delay/30', timeout=1))

for i in range(5):
  futures.append(session.get('http://httpbin.org/status/200'))

print "sleeping"
sleep(10)

print "retrieving"
while futures:
  future = futures.pop()
  try:
    print "res: %s" % future.result().content
  except Exception as e:
    print "exc: %s" % e

sleep(10)

print "more"
for i in range(5):
  futures.append(session.get('http://httpbin.org/status/200'))

sleep(10)
print "done"
while futures:
  future = futures.pop()
  try:
    print "res: %s" % future.result().content
  except Exception as e:
    print "exc: %s" % e
sleep(10)
````

the number of (sub) processes always equals the number of workers i pick.

```
$ pstree -p 5262
python(5262)─┬─{python}(5268)
             ├─{python}(5269)
             ├─{python}(5270)
             └─{python}(5271)
```

**Comment by rififi** [comment]
My bad, indeed you are right. My futureSession was in in a PyQt thread, and I was trying to shutdown the session in the _del_ method of the thread, which wasn't called for an unknown reason.
