### ISSUE TITLE
session parameter doesn't exist in FuturesSession constructor

### ISSUE THREAD

**Issue by silverAndroid** [ross/requests-futures#29]
When I try to use an existing session from the `requests` module, it crashes saying 

    Traceback (most recent call last):
      future_session = FuturesSession(session=my_session)
      File "/usr/local/lib/python3.4/dist-packages/requests_futures/sessions.py", line 41, in __init__
      super(FuturesSession, self).__init__(*args, **kwargs)
     TypeError: __init__() got an unexpected keyword argument 'session'

although it says in the documentation to do so

**Comment by ross** [comment]
If you're pulling down the latest version from pipy it doesn't yet include the session PR #28. If you need that ASAP you can install from git. Otherwise I'll make a note to cut another release, but it might take me a big to get to it.

**Comment by silverAndroid** [comment]
No it's not urgent, the git install worked perfectly!
