### ISSUE TITLE
Using streaming with requests-futures

### ISSUE THREAD

**Issue by pkch** [ross/requests-futures#34]
It would be nice to update the docs to say whether or not it's possible to use requests-futures to achieve asynchronous processing of data coming through a streaming HTTP request (where `stream=True` is set in the `request` call). 

Perhaps adding an example of how to do it, or else just stating that it won't work.

My attempts to figure it out from the docs and trial and error [failed](http://stackoverflow.com/questions/37282936/asynchronous-processing-of-streaming-http-with-requests-requests-futures).

**Comment by ross** [comment]
> Perhaps adding an example of how to do it, or else just stating that it won't work.

I wouldn't expect it to work. The way things are currently written the callback is passed the full response so would  wait until everything is back before invoking it. It might be possible to rework things, maybe adding another streaming friendly callback, but I'm not 100% sure what that would look like.

**Comment by pkch** [comment]
That makes sense. 

I think callback can't work with streaming, if `requests-futures` only uses public API of `request`: the only way intermediate results are exposed in the public API is through the blocking iterator `iter_lines`. But I'm really not experienced in this at all, so maybe I just don't see something obvious.

**Comment by ross** [comment]
Maybe if you describe your use case/reason for needing streaming in an async env I might be able to help. My intuition is that there's not a lot of cases where it'd buy much, but I wouldn't rule out that some could exist.

**Comment by pkch** [comment]
My use case is not too impressive. Just wanted to use Twitter streaming API to retrieve tweets in real-time, and then display update when something interesting happened - without blocking the main program.

**Comment by ross** [comment]
> My use case is not too impressive. Just wanted to use Twitter streaming API to retrieve tweets in real-time, and then display update when something interesting happened - without blocking the main program.

Ah. In that sort of setup you'd likely be better off directly using [threading.Thread](https://docs.python.org/2/library/threading.html#thread-objects) to create a (background) thread that makes the requests calls and does the stream processing. The futures paradigm pretty much just gets in the way there. Good luck.
