### ISSUE TITLE
Thoughts on accessing the request body on failure

### ISSUE THREAD

**Issue by erchn** [ross/requests-futures#36]
Hi there,

I have requests-futures running very nicely (nice work!!), even using a Retry object from urllib3 and all is working great.  In my background_callback I have status checking and on failure, I'd love to log the post data I sent for trying again later or just general debug.

I've tried setting the post_data as an attribute of the session, but it gets overwritten the next time I loop thru and use the FuturesSession again for the next request.

Would using the ProcessPoolExecutor get around this issue given that the session would be forked at that point?

Thanks!
Ethan

**Comment by erchn** [comment]
Maybe #5 solves my issue?

**Comment by erchn** [comment]
Hmm, that didn't seem to help, not exactly sure why.  Tried using a lambda as the callback while pass the post_data as a third argument to the real callback function and it seems like the passed data is still getting overwritten.  Even when using copy.copy or deepcopy in the definition of the lambda. Odd.

A few details, here's the session definition

    # make normal requests session with retry logic
    sesh = Session()
    sesh.mount('https://', HTTPAdapter(
               max_retries=Retry(total=5,
                                 status_forcelist=[500])))
    # use requests session in futures enabled session
    session = FuturesSession(session=sesh, max_workers=8)

Then later in a loop

    futures.append(session.post(url,
                                    data=json.dumps(buf),
                                    headers=headers,
                                    timeout=(2, 5),
                                    background_callback=lambda sess, resp: check_failure(sess, resp, buf.copy())
                                    ))
 
Finally the cb function

    def check_failure(sess, res, abuf):
        logging.debug("successful send of {} docs".format(len(abuf)))


That logging line will show the size of a buffer and then go all zeros, even though it's sending data, it sees the length of `abuf` as 0.  Which is likely true in the main processing function by the time that future is processed.

Any ideas would be helpful.  Maybe I'm trying to do too much and should just use futures directly.

Thanks!

**Comment by ross** [comment]
> Any ideas would be helpful. Maybe I'm trying to do too much and should just use futures directly.

What you're aiming at should be possible. Just a matter of tracking down what's going wrong.

I have 2 suggestions that are just minor tweaks to try and help track down what's going on. The first would be to assign buf.copy() to a variable and use that in the lambda. I don't think that will make a difference, but it shouldn't hurt to try it. Second would be to do the first, but go ahead and take the length as part of the assignment. Anyway, the two of those are aiming to track down potential problems in whatever buf.copy is returning. Since I don't know what it is maybe there's some weird behaviors with it that are getting in the way.

**Comment by erchn** [comment]
Well, buf is just a plain list of dict objects.  Assigning to a temporary variable didn't help.  Sending the count also didn't help, it seems to have the save value as the callback logging of others, even though it should never be the same.  It's almost like the callbacks are getting overwritten by the next call on that session.

**Comment by ross** [comment]
Sorry didn't pay close enough attention to what you were trying to do. That one actually came up in https://github.com/ross/requests-futures/issues/33#issuecomment-219425226. Plenty of detail there, but basically python acts like pass by reference.

**Comment by erchn** [comment]
I assumed, incorrectly, that buf.copy() of buf[:] would have provided a new object so it wouldn't be pass by ref, but I guess not. :-/

Thanks.
