### ISSUE TITLE
Problem with requests-futures and Hyper's HTTP20Adapter

### ISSUE THREAD

**Issue by bek0s** [ross/requests-futures#37]
Has anybody tried to user requests-futures with the `HTTP20Adapter` of the Hyper library? 

This my initialization code:
```python
session = requests.session()
session.mount(url, hyper.contrib.HTTP20Adapter())
executor = concurrent.futures.ThreadPoolExecutor(
    max_workers=multiprocessing.cpu_count())
future_session = requests_futures.sessions.FuturesSession(
    executor=executor, session=session)
```

Now if I run the following code once it will work just fine:

```python
future = future_session.post(url, json=resource)
result = future.result()
```

However, if I put the above two lines in a loop, the HTTP server will send as many requests as the number of workers specified on the executor. After that the client will halt/block/freeze and the server will receive no further requests. If I press Ctrl+C on the client the last call is always this: 

```
File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

If I put an 1 second delay between the requests the problem goes away (but of course this is very slow). Also, if I use hyper's `HTTPAdapter` instead of `HTTP20Adapter` then it works just fine.

The server where I am posting data is nginx http2 enabled. If I try to use grequests with Hyper's `HTTP20Adapter` everything works just fine.

Does anybody else have the same problem? Thanks!

**Comment by ross** [comment]
That seems to be more of a locking problem with hyper than anything to do with requests-futures. From the looks of it hyper [explicitly states it's not thread-safe](https://github.com/python-hyper/hyper-h2/blob/master/docs/source/advanced-usage.rst#thread-safety) so I wouldn't expect it to work. Sorry, but I don't know enough about grequests to know whether you're safe there or just lucky.
