### ISSUE TITLE
Override docs in FuturesSession to report the Future return type

### ISSUE THREAD

**Issue by kenzierocks** [ross/requests-futures#38]
PyCharm uses the `:rtype` documentation present in `requests`' functions to determine the return type of functions, but `FuturesSession` does not override the docs to state that they return a `Future` instead. I'm not sure how easy this would be considering the need to support the backport library, but it would be a nice thing to do.

**Comment by ross** [comment]
Not familiar with PyCharm's use of `:rtype` or how that stuff works. It'd be easy enough to modify the doc on `FuturesSession.request` if that'd do it. The only place I see that is `requests.Session.request` (outside of the non-session calls.) Anyway, not something I'm likely to have the time to dig into enough to figure out what needs to happen and test, but I'd happily accept a patch.

**Comment by JJayet** [comment]
Nice !
We can close this now :)
