### ISSUE TITLE
Factually incorrect call to Sessions#__init__

### ISSUE THREAD

**Issue by jon-torodash** [ross/requests-futures#41]
https://github.com/ross/requests-futures/blob/master/requests_futures/sessions.py#L54

suggests that requests.Session#__init__ takes **kwargs, but this does not seem to be the case in the latest or any other recent versions:

https://github.com/kennethreitz/requests/blob/v2.12.4/requests/sessions.py#L308

Attempting to use them throws an exception.

**Comment by ross** [comment]
That's actually done so to be future proof. If/when args/kwargs are added to `Session.__init__` you'd be able to use them with requests-futures. The error message/failure should be pretty much the same thing you get if you were to try and pass params to `Session()` so it *shouldn't* hurt anything to have them there.
