### ISSUE TITLE
Documentation for Cancelling is in correct.

### ISSUE THREAD

**Issue by DonGar** [ross/requests-futures#43]
The readme includes this example code, and claims that it will cancel the future2, future3 requests.

```
from requests_futures.sessions import FuturesSession
with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get')
    future2 = session.get('https://httpbin.org/delay/10')
    future3 = session.get('https://httpbin.org/delay/10')
    response = future.result()
```

Testing with python3.5, this isn't true. Exiting the context manager takes at least 10 seconds, which shows that any in-progress requests are run to completion.

**Comment by ross** [comment]
`Session.__exit__` calls `ThreadPoolExecutor.shutdown`. "cancel" is a slightly strong word for what's happening, but still accurate. In-progress requests won't be immediately killed/abandoned, they will complete as normal. Anything still queued and not yet started won't be kicked off though as the executor won't pick them up. Killing the in-flight stuff could be messy and potentially cause problems in cases where the script will continue to live on and do other work.

If you specifically need to kill things immediately you might take a look at [canceling the exector's _threads](https://gist.github.com/clchiou/f2608cbe54403edb0b13). I haven't tried that so no clue how well it'd work and what sort of state that would leave things in. 

If you want to PR something that elaborates on the cancel behavior I'll take a look at it.

/cc https://github.com/ross/requests-futures/pull/39
