### ISSUE TITLE
Is it possible to use checkpoint with requests-futures to cache the results?

### ISSUE THREAD

**Issue by vkchan** [ross/requests-futures#44]
I would like to use request-futures with ediblepickle checkpoint, to fetch and parse a list of URLs asynchronously (one cache file per URL), as the list of URLs may change in the future (new pages added). How can we properly do it with requests-futures?

I typed up my questions here, any insights would be greatly appreciated. Thanks!
http://stackoverflow.com/questions/43164804/how-to-properly-use-checkpoint-to-cache-results-from-asynchronous-web-requests-i

**Comment by ross** [comment]
Seems like there's an impedance mismatch between the 2 tools you've chosen and the problem you've set up to solve. 

You want to cache individual urls which `checkpoint` does, but that won't allow you to batch up the misses and take advantage of requests futures. If you want to go that route you'd need to do your own futures and have the `submit`ed methods call something that's decorated with `checkpoint`. 

in pseudo-code, haven't seen checkpoint before so no clue whether it can work like this, it may or may not be thread safe.

```python
class Something(object):

    def __init__(self):
        self.sess = Session()  # not a FuturesSession
        self.executor = ThreadPoolExecutor()

    @checkpoint(<whatever goes here, assuming it can decorate a object method>)
    def fetch_url(self, url):
        resp = self.sess.get(url)
        # processing here
        return caption_list

    def fetch_urls(self, urls):
        futures = {u: self.executor.submit(self.fetch_url, u) for u in urls}
        return {u: f.result() for u, f in futures.items()]

s = Something()
results = s.fetch_urls(urls)
```

Another option would be to manage the caching yourself and use requests futures for the misses. 

```python

class Something(object):

    def __init__(self):
        self.sess = FuturesSesson()

    def fetch_urls(self, urls);
        results = {}
        misses = {}
        for url in urls:
            cached = self.get_from_cache(url)
            if cached:
                results[url] = cached
            else:
                misses[url] = self.sess.get(url)
        results.merge({u: self.process_response_and_cache(f.result()) for u, f in misses.items()})
        return results

s = Something()
results = s.fetch_urls(urls)
```

Anyway both of those are just sketches/starting points. The actual solutions would be more involved and likely cleaner/clearer if i were writing them up for real.

Given that this question is really about how to solve a general problem with caching and async and not how to do something specific to requests_futures or checkpoint SO is probably the right place to ask.

**Comment by vkchan** [comment]
Thanks a lot for your suggestions!
