### ISSUE TITLE
cancellation not working?

### ISSUE THREAD

**Issue by nschloe** [ross/requests-futures#48]
I'm reading the example
```python
from requests_futures.sessions import FuturesSession
with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get')
    future2 = session.get('https://httpbin.org/delay/10')
    future3 = session.get('https://httpbin.org/delay/10')
    response = future.result()
```
such that there a three requests on one worker, but really only one result is expected, so two of the futures get canceled. Hence, the above code snipped should take just about as long as
```python
from requests_futures.sessions import FuturesSession
with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get')
    response = future.result()
```
I noticed however that it takes as long as
```python
from requests_futures.sessions import FuturesSession
with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get')
    future2 = session.get('https://httpbin.org/delay/10')
    future3 = session.get('https://httpbin.org/delay/10')
    response = future.result()
    response2 = future2.result()
    response3 = future3.result()
```
in other words: the remaining futures do _not_ get canceled.

Perhaps a misunderstanding on my side?

**Comment by ross** [comment]
In flight requests are not automatically canceled when the block exits. The ThreadPoolExecutor is shutdown:

https://github.com/ross/requests-futures/blob/5ebe6c135486bd36f919ab6aa2bf5b0b774ea0ed/requests_futures/sessions.py#L98-L99

Shutdown waits for things to complete (by default) https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown

> If wait is True then this method will not return until all the pending futures are done executing and the resources associated with the executor have been freed. If wait is False then this method will return immediately and the resources associated with the executor will be freed when all pending futures are done executing. Regardless of the value of wait, the entire Python program will not exit until all pending futures are done executing.

**Comment by nschloe** [comment]
Alright, thanks for the explanation!

**Comment by ross** [comment]
NP. Fwiw, I had to dig into it to be sure what the behavior was 😃

**Comment by vojtechkral** [comment]
I just ran into this as well. It seems to me that the [paragraph](../../#canceling-queued-requests-aka-cleaning-up-after-yourself) in the README is confusign or perhasp even wrong. It seems to indicate the 2nd and 3rd requests will be skipped, but that's not the case, they will be finished exactly as if they were waited on with a `.result()` call.

**Comment by ross** [comment]
Yeah as written that doesn't really make sense with the state of the lib:

```python
#!/usr/bin/env python

from datetime import datetime
from requests_futures.sessions import FuturesSession

print('start: {}'.format(datetime.now()))
with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get')
    future2 = session.get('https://httpbin.org/delay/10')
    future3 = session.get('https://httpbin.org/delay/10')
    print('before: {}'.format(datetime.now()))
    response = future.result()
    print('after: {}'.format(datetime.now()))
print('end: {}'.format(datetime.now()))
```

```bash
(env)otter:requests-futures ross$ PYTHONPATH=. ./fetch.py
start: 2017-11-10 05:34:41.713153
before: 2017-11-10 05:34:41.718653
after: 2017-11-10 05:34:42.177363
end: 2017-11-10 05:35:02.813289
```

I'm not really sure there's a clean way to update it to make sense. Even canceling the futures doesn't result in things imediately stoping it just prevents un-started stuff from kicking off:

```python
#!/usr/bin/env python

from datetime import datetime
from pprint import pprint
from requests_futures.sessions import FuturesSession


def callback(*args):
    pprint(args)


print('start: {}'.format(datetime.now()))
with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get',
                         background_callback=callback)
    future2 = session.get('https://httpbin.org/delay/10',
                          background_callback=callback)
    future3 = session.get('https://httpbin.org/delay/10',
                          background_callback=callback)
    print('before: {}'.format(datetime.now()))
    response = future.result()
    print('after: {}'.format(datetime.now()))
    future2.cancel()
    future3.cancel()
print('end: {}'.format(datetime.now()))
```

```bash
(env)otter:requests-futures ross$ PYTHONPATH=. ./fetch.py
start: 2017-11-10 06:06:27.891404
before: 2017-11-10 06:06:27.896662
(<requests_futures.sessions.FuturesSession object at 0x108c90ad0>,
 <Response [200]>)
after: 2017-11-10 06:06:28.275488
(<requests_futures.sessions.FuturesSession object at 0x108c90ad0>,
 <Response [200]>)
end: 2017-11-10 06:06:38.820204
```

Even adding `wait=False` to the shutdown call only causes the block to exit quickly, but the work still continues. May be best to just remove that section.
