### ISSUE TITLE
Prepared FutureSession Request

### ISSUE THREAD

**Issue by kylelt** [ross/requests-futures#49]
In the standard requests library i can do `req = requests.Request( ..., ..., ... )` to prepare a request
Is there an equivalent for requests-futures I have tried the novel approach of using a FutureSession to send a prepared request but no dice, it returns standard responses slowly which makes me believe that it performs the requests synchronously see what i am currently trying below:

```
futures = []
with FutureSession(exec=... ,session=existingRequestsSession) as fs:
    for x in toRequest:
        req = requests.Request(...,
            ...,
            ...,
        )

        prep = req.prepare()
        futures.append(fs.send(prep))

# wait for everyone to finish
responses = [x.result() for x in futures]

# Gives errors like:
# object of type Response has no method result()
```

**Comment by ross** [comment]
Interesting. That's not a case that's currently handled. When you call `fs.send` it's calling the normal method on the base `Session` object, https://github.com/requests/requests/blob/e86df6e0eb4e7779cfd61bcf4d88d5c51c4e7eef/requests/sessions.py#L589.

It should be possible to wrap `send` in a [manner similar to the existing `request`](https://github.com/ross/requests-futures/blob/5ebe6c135486bd36f919ab6aa2bf5b0b774ea0ed/requests_futures/sessions.py#L67).

**Comment by kavink** [comment]
Is it similar to #21  ?

**Comment by ross** [comment]
It is. Totally forgot about that issue/thread. ☹️
