### ISSUE TITLE
Add args to background callbacks

### ISSUE THREAD

**Issue by earada** [ross/requests-futures#5]
Background callback args are fixed for now, but I need pass some additional information to the callback in my code.

I suggest this request function in order to allow callbacks with arguments passed by the caller code.

``` python
    def request(self, *args, **kwargs):
        """Maintains the existing api for Session.request.

        Used by all of the higher level methods, e.g. Session.get.

        The background_callback param allows you to do some processing on the
        response in the background, e.g. call resp.json() so that json parsing
        happens in the background thread.
        """
        func = sup = super(FuturesSession, self).request

        background_callback = kwargs.pop('background_callback', None)
        background_callback_args = kwargs.pop('background_callback_args', None)
        if background_callback:
            def wrap(*args_, **kwargs_):
                resp = sup(*args_, **kwargs_)
                if background_callback_args:
                    background_callback(self, resp, *background_callback_args)
                else:
                    background_callback(self, resp)
                return resp

            func = wrap

        return self.executor.submit(func, *args, **kwargs)
```

Example usage:

``` python
id = ...
future = session.get(url, background_callback=fun_cb, background_callback_args=(id,))
```

**Comment by crazygit** [comment]
meet the same question, work out it followed as @ross 
> http://stackoverflow.com/questions/938429/scope-of-python-lambda-functions-and-their-parameters
>When a lambda is created, it doesn't make a copy of the variables in the enclosing scope that it uses. It maintains a reference to the environment so that it can look up the value of the variable later. There is just one m. It gets assigned to every time through the loop. After the loop, the variable m has value 'mi'. So when you actually run the function you created later, it will look up the value of m in the environment that created it, which will by then have value 'mi'.

>One common and idiomatic solution to this problem is to capture the value of m at the time that the lambda is created by using it as the default argument of an optional parameter. You usually use a parameter of the same name so you don't have to change the body of the code:
>```
for m in ('do', 're', 'mi'):
   funcList.append(lambda m=m: callback(m))
```
so, @yulyt 
```
 session.get('%s%s' % (schema, hostname),
                    background_callback=lambda sess, resp, hostname=hostname: bg_call(sess, resp, hostname),
                    timeout=2)
```
will work.

**Comment by yulyt** [comment]
I see,  I understand the issue. Thanks for the references @ross and @crazygit :-)
