### ISSUE TITLE
How to prevent closing while there are scheduled requests?

### ISSUE THREAD

**Issue by Granitosaurus** [ross/requests-futures#50]
I'm having this simple concurrent pagination downloader:

    def response(func):
        def wrap(self, response):
            return func(self, response.result())
        return wrap

    class Downloader:
        def __init__(self, url):
            self.session = FuturesSession(max_workers=3)
            self._request(url, self.parse_start)

        def _request(self, url, callback):
            print(f'scheduling: {url}')
            future = self.session.get(url)
            future.add_done_callback(callback)

        @response
        def parse_start(self, response):
            total_pages = 100 # find pages in response html source
            for page in range(2, total_pages):
                url = 'http://turtlekebab.com/page=2'.replace('2', str(page))
                self._request(url, self.parse)

        @response
        def parse(self, response):
            print(f'parsing {response.url}')

The issue I'm having is if my program has nothing else to do after scheduling the scheduled requests are forgotten and the program ends.  
How do I ensure the queued up requests are being finished?

**Comment by ross** [comment]
In general futures aren't intended handle things with callbacks. The callback mechanism is more for applying some processing/transformations to the response before your application handles them via the futures object. If the future object goes out of scope the handle to get at the response will be lost and as you've seen nothing will be blocking/waiting for things to finish. Generally you need to save up the futures objects and call `resp = future.result()` on them or `resp = yield future`, as appropriate, to get at the response. Those will block or wait until things are done.

**Comment by Granitosaurus** [comment]
So `future.result()` will block, right? That kinda defeats the whole purpose of async framework.  

An alternative would be to keep looping through futures and pop the ones that resolve to `future.done()`? Is there a reasonable shortcut for this?

**Comment by ross** [comment]
There's 2-main styles of async: futures (also referred to as promises) and callbacks. Python in general seems to prefer the futures route. In general it results in much easier to follow code and avoids "callback-hell", but there's a time and place for both.

The critical bit with future objects is that they're a handle to the result. You get them back immediately while the work happens in the background and can go about doing other things until you need the result. At that point you can get at it with future.resp() or yeild future.

You can take a look at the README for dirt simple examples and [a blog post I wrote around the same time](https://www.xormedia.com/high-performance-web-asynchronous-http/) for how this works specifically with requests futures. For a more general discussion of futures see https://en.wikipedia.org/wiki/Futures_and_promises.
