### ISSUE TITLE
Compatibility with asyncio.Future

### ISSUE THREAD

**Issue by aparamon** [ross/requests-futures#57]
Currently, `FuturesSession` objects are not `await`able, as they implement `concurrent.futures.Future` not `asyncio.Future`.

It is proposed that `requests_futures` (additionally?) provides `asyncio.Future` interface, eliminating the need for boilerplate `asyncio.wrap_future()` calls.

**Comment by acarl005** [comment]
Agreed! It was very confusing when I tried to `await` a future from a `session.get` call only to get this error:

```
TypeError: object Future can't be used in 'await' expression
```

**Comment by timurgen** [comment]
This one would be very useful to have!
