### ISSUE TITLE
Proxies do not behave as they should

### ISSUE THREAD

**Issue by Granitosaurus** [ross/requests-futures#58]
Proxie behaviour is completely unpredictable and does not match `requests` proxy behaviour:

    session = FuturesSession()
    proxy = 'https://username:password@31.171.152.51:80'
    url = 'https://httpbin.org/ip'
    resp = session.get(url, proxies={'https': proxy}, timeout=5)
    try:
        print(resp.result())
    except ProxyError as e:
        print(e)
    # with synchronious
    session = requests.session()
    resp = session.get('http://httpbin.org/ip',
                       proxies={'https': proxy})
    print(resp)

returns: 

    HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
    <Response [200]>

I've used free proxies available from here for testing: https://nordvpn.com/free-proxy-list/

Edit: I'm having trouble replicating a lot of things. Seems like even requests itself proxy implementation is full of issues.

**Comment by ross** [comment]
That error message is what I get when I put a non-routable IP address in for the proxy, e.g. 192.0.2.42 (from the documentation CIDR.) 

If I pull one of the free proxy IPs off of https://nordvpn.com/free-proxy-list/ and us it things work fine, but I don't have a valid username and password for it (but it fails the same with or without requests_futures. I can't think of anything that would be different about requests futures and proxies either. 

```python
#!/usr/bin/env python

from requests_futures.sessions import FuturesSession
from requests.exceptions import ProxyError
import requests

session = FuturesSession()
proxy = 'http://161.68.250.139:80'
url = 'http://httpbin.org/ip'
resp = session.get(url, proxies={'http': proxy}, timeout=5)
try:
    print(resp.result())
except ProxyError as e:
    print(e)
# with synchronious
session = requests.session()
resp = session.get('http://httpbin.org/ip',
                   proxies={'http': proxy})
print(resp)
```

```
(env)otter:tmp ross$ ./proxy.py
<Response [407]>
<Response [407]>
```

**Comment by Granitosaurus** [comment]
Yeah you're right. I think the inconsistency with https proxies and issues I'm facing are actually issues of `requests` and digging further seems like issues with python itself as well.  

I'm closing the issue untill I figure out more, but aside from confusing error output I don't think request-futures is faulty here.
