### ISSUE TITLE
Example of callback for large number of requests

### ISSUE THREAD

**Issue by serain** [ross/requests-futures#61]
All of the examples in the README are for 2-3 requests.

I have a case where I would like to launch around 10,000 requests from a `urls` array, across a dozen workers, and run an action when the responses have returned (lets say `print(url, response.code)`).

I'm familiar wih the [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html) examples from the Python3 docs but it remaines unclear to me if and how and I can fire and forget an array of urls with `requests-futures`, and perform an action whenever the responses come in.

As I imagine this is be quite a common use case for some users, an snippet example would be useful.

**Comment by ross** [comment]
There's nothing fundamentally different when working with 10k than 2. You'd probably want to collect the futures in an array and then use something like `as_completed` to iterate over them as they finish.

```python
#!/usr/bin/env python

from concurrent.futures import ProcessPoolExecutor, as_completed
from requests import Session
from requests_futures.sessions import FuturesSession

session = FuturesSession(executor=ProcessPoolExecutor(max_workers=10),
                         session=Session())

urls = ['https://httpbin.org/get?i={}'.format(i) for i in range(5)]

futures = []
for url in urls:
    future = session.get(url, timeout=5)
    futures.append(future)

for future in as_completed(futures):
    # you may want to handle exceptions here
    resp = future.result()
    print(resp.request.url, resp.status_code)
```

```
(env)otter:tmp ross$ ./waiting.py
https://httpbin.org/get?i=1 200
https://httpbin.org/get?i=4 200
https://httpbin.org/get?i=2 200
https://httpbin.org/get?i=3 200
https://httpbin.org/get?i=0 200
```
