### ISSUE TITLE
post files with multiprocessor

### ISSUE THREAD

**Issue by YunzhaoLu** [ross/requests-futures#62]
I have a python program with tornado.ioloop to serve websocket connections.
I defined a future session in the main outside ioloop, and I call the session to post file in different websocket connection, and got following error:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.BufferedReader' object

Your advice will be highly appreciated.

Regards,
Luke

**Comment by ross** [comment]
Python threads aren't true/full multithreading. There's some talk about it [here](https://stackoverflow.com/questions/12758952/green-threads-and-thread-in-python). It's threading model works well for when you are trying to parallelize multiple http requests at once and waiting on the servers to do some work (in parallel) before dealing with the responses. As you've seen though it doesn't actually allow work to happen in parallel on the client side so it's not helpful for trying to parallelize uploads. You'll need to do multiple processes to get that, not really a case that requests-futures was designed for.
