### ISSUE TITLE
Unresolved attribute reference 'result' for class 'Response'

### ISSUE THREAD

**Issue by rodrigozanatta** [ross/requests-futures#65]
Just a boring thing. Copy and paste the first example in Pycharm 2018.2.4. It run but you get a warning inspection with: 

**Unresolved attribute reference 'result' for class 'Response' less...** (Ctrl+F1) 
Inspection info: This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items

How to fix it? Just some import I didn't find. From where is this **result** function?

**Comment by ross** [comment]
Can you drop a code snipping in here. I'm not 100% sure what would be going on. In general `.result()` is the call that's made on a `Future` object to grab it's result when you need it. The fact that it's not defined makes me think that the object the call is being made on isn't something being returned by a `FutureSession`.

**Comment by rodrigozanatta** [comment]
Lol, sorry. As I say, the code is just your first example:

```
from requests_futures.sessions import FuturesSession

session = FuturesSession()
# first request is started in background
future_one = session.get('http://httpbin.org/get')
# second requests is started immediately
future_two = session.get('http://httpbin.org/get?foo=bar')
# wait for the first request to complete, if it hasn't already
response_one = future_one**.result()**
print('response one status: {0}'.format(response_one.status_code))
print(response_one.content)
# wait for the second request to complete, if it hasn't already
response_two = future_two**.result()**
print('response two status: {0}'.format(response_two.status_code))
print(response_two.content)
```
Only need to import something...

**Comment by ross** [comment]
The objects are https://docs.python.org/3/library/concurrent.futures.html. Same interface in 2.7.

I can assure you the examples work :grin: so not sure what's going wrong for you. 

```
$ virtualenv env
$ source env/bin/activate
$ pip install requests_futures
$ python run example.py
...
```

**Comment by rodrigozanatta** [comment]
Hum... I think I just find the problem now. You use:

`from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor`

There is the object **concurrent.futures.Future.** Maybe what I need is this:

`from concurrent.futures.Future import result`

I will try when I went home. By the way, the code work, just show this borring warning.

**Comment by rodrigozanatta** [comment]
Didn't work. I just don't understand. Do it yourself, install the comunity version of PyCharm and try to run the code. Do you see the warning?

**Comment by ross** [comment]
Sorry I don't make use of PyCharm. Pretty safe to assume something is up with your setup or the exact  steps you're taking rather than requests-futures.
