### ISSUE TITLE
max_workers default value is too low

### ISSUE THREAD

**Issue by dchevell** [ross/requests-futures#66]
The default `max_workers` value is **2**, which seems extremely low to be a default. The `concurrent.futures` library itself has much higher defaults for `ThreadPoolExecutor`s at 5 * CPU cores (e.g. a 4 core machine would have 20 threads).

I've seen some libraries that use `requests-futures` naively using the default. I'd like to suggest one of the following:

1. Increase the default to something more beneficial, e.g. **5**
2. Use the standard `concurrent.futures` default value (my preferred solution)

The only problem with option 2 is that in Python 3.3 and 3.4 `max_workers` had no default value for ThreadPoolExecutors and *had* to be specified. This is easy enough to work around by implementing the same method `concurrent.futures` itself [introduced in Python 3.5](https://github.com/python/cpython/blob/3.5/Lib/concurrent/futures/thread.py#L91):

```python
import os

class FuturesSession(Session):

    def __init__(self, executor=None, max_workers=None, session=None,
                 adapter_kwargs=None, *args, **kwargs):
        # ...
        if max_workers is None:
            max_workers = (os.cpu_count() or 1) * 5
```

Would be happy to open a PR for this, but before doing so wanted to open this in case there's a hard requirement for this low default value I'm not aware of.

**Comment by dchevell** [comment]
Just to give you an idea of _how_ much difference this makes, consider the following example:

```python
# futurespeed.py
import concurrent.futures
from requests_futures.sessions import FuturesSession

session = FuturesSession()
futures = [session.get('http://httpbin.org/get') for i in range(1, 1000)]
concurrent.futures.wait(futures)
```

Using current default value:
 ```bash
$ time python futurespeed.py
python futurespeed.py  3.43s user 0.34s system 1% cpu 3:28.98 total
```
Runtime: 3 minutes, 28 seconds

After making the modifications suggested above and pip installing my local dev version:
 ```bash
$ pip install -U ~/Development/requests-futures
$ time python futurespeed.py
python futurespeed.py  2.85s user 0.30s system 45% cpu 6.887 total
```
Runtime: 6.8 seconds

**Comment by ross** [comment]
I'd support a higher default than 2, but I'd be hesitant to go all the way to `cpu_count()` * 5 as that'd pretty easily beat a small server to death. I can see that making sense if you're number crunching or otherwise doing something "in parallel" on a local system, but it doesn't make as much sense when you're hitting a remote service. 

4 or 5 would be OK. The other thing it'd probably be worth doing is documenting the default. There's plenty of bits in the README about setting max_workers, but nothing so far as I can tell that calls out what the default is. Would appreciate it if you found a good place to say what the default is in there if you PR the change.

**Comment by dchevell** [comment]
> I'd be hesitant to go all the way to cpu_count() * 5 as that'd pretty easily beat a small server to death.

That's what I figured the reason to be, but how true is that these days?

I run [pi-hole](https://pi-hole.net) on a raspberry pi, so I used that as an example of an extremely small server running a nontrivial application. The index page executes PHP to render and performs multiple queries against a local sqlite database, so there's a CPU and I/O work cost per request. I ran the same test as above, with 40 threads (my default of 8 cores * 5). The full run of 1000 requests took 1:28 to complete, and the application remained accessible throughout the test.

These days I would be surprised if this much load _would_ beat a small server to death - my example server has to be at the far end of the bell curve for power & performance.

**Comment by dchevell** [comment]
Oh, and you do actually call out the default in the README:

> By default a ThreadPoolExecutor is created with 2 workers.

**Comment by ross** [comment]
> These days I would be surprised if this much load _would_ beat a small server to death - my example server has to be at the far end of the bell curve for power & performance.

Yeah, but your example app is probably on the far end of simple as well. 😁 

In general agree that 2 is lower than it needs to be, but don't want to make the default as aggressive as  5x cpu. E.g. on the normal boxes I use at work that would be 5 * 40 = 200. A fixed number of 4-6 for the default seems appropriate.



> > By default a ThreadPoolExecutor is created with 2 workers.

Heh. Cool. That can just be bumped. I searched for `max_workers` and didn't see a 2 there.

**Comment by dchevell** [comment]
How about 8 :D That’s high enough to provide a tangibly improved default but is a long, long way from dangerous

**Comment by ross** [comment]
OK
