### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by haoyuanli** [ross/requests-futures#91]
Maybe I need a Monday coffee to refresh myself, but may i ask what this means?

```
This means that only Python 3.5 is fully supported, while Python versions 3.4 and above REQUIRE an existing requests.
```
why is it 3.4 and above?

Thanks

**Comment by ross** [comment]
That's just for ProcessPoolExecutor, and tbh that may be out of date. In general I'd discourage the use of ProcessProolExecutor. ThreadPoolExecutor is almost certainly going to be easier to use since things won't have to cross process boundaries.

**Comment by haoyuanli** [comment]
cool, thanks
